version: '3.8'

services:
    postgres:
        container_name: postgres
        image: postgres
        environment: 
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - postgres
        restart: unless-stopped

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-postgres}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-postgres}
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "5050:80"
        networks:
            - postgres
        restart: unless-stopped

networks:
    postgres:
        driver: bridge # for linux containers
       # driver: nat # for windows containers
    
volumes:
    postgres:
    pgadmin: